MallocNanoZone=0
USER=wosewick
COMMAND_MODE=unix2003
__CFBundleIdentifier=com.microsoft.VSCode
PATH=/Users/wosewick/.vscode/extensions/ms-python.python-2024.8.1/python_files/deactivate/zsh:/Users/wosewick/Development/code/phase-3/python-project/MuFO---pygame/.venv/bin:/Users/wosewick/.pyenv/shims:/Users/wosewick/.nvm/versions/node/v20.11.1/bin:/Users/wosewick/.vscode/extensions/ms-python.python-2024.8.1/python_files/deactivate/zsh:/Users/wosewick/Development/code/phase-3/python-project/MuFO---pygame/.venv/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/wosewick/.vscode/extensions/ms-python.python-2024.8.1/python_files/deactivate/zsh:/Users/wosewick/Development/code/phase-3/python-project/MuFO---pygame/.venv/bin:/Users/wosewick/.nvm/versions/node/v20.11.1/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin
LOGNAME=wosewick
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.zwtLrgSSXP/Listeners
HOME=/Users/wosewick
SHELL=/bin/zsh
TMPDIR=/var/folders/tk/x0h7y01j7w3fq_pxsmv_6q3h0000gn/T/
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
XPC_SERVICE_NAME=0
XPC_FLAGS=0x0
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
SHLVL=1
PWD=/Users/wosewick/Development/code/phase-3/python-project/MuFO---pygame
OLDPWD=/Users/wosewick/Development/code/phase-3/python-project/MuFO---pygame
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man:/Library/Developer/CommandLineTools/usr/share/man:/Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/share/man:/Users/wosewick/.nvm/versions/node/v20.11.1/share/man:/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:/opt/homebrew/share/info:
NVM_DIR=/Users/wosewick/.nvm
NVM_CD_FLAGS=-q
NVM_BIN=/Users/wosewick/.nvm/versions/node/v20.11.1/bin
NVM_INC=/Users/wosewick/.nvm/versions/node/v20.11.1/include/node
PYENV_SHELL=zsh
PIPENV_VENV_IN_PROJECT=1
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.90.2
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/tk/x0h7y01j7w3fq_pxsmv_6q3h0000gn/T/vscode-git-e4996c548d.sock
VIRTUAL_ENV=/Users/wosewick/Development/code/phase-3/python-project/MuFO---pygame/.venv
VIRTUAL_ENV_PROMPT=MuFO---pygame
VSCODE_INJECTION=1
ZDOTDIR=/Users/wosewick
USER_ZDOTDIR=/Users/wosewick
TERM=xterm-256color
PS1=MuFO---pygame%n@%m %1~ %# 
_=/usr/bin/python3
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CPATH=/usr/local/include
LIBRARY_PATH=/usr/local/lib
